version: '3.8'

services:
  et-database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: eticket
      MYSQL_USER: cinemafan
      MYSQL_PASSWORD: ILov<3movi3s
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  et-php:
    container_name: php
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/eticket
    depends_on:
      - et-database
  et-nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/eticket
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - et-php
      - et-database
  et-adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - et-database
